export const TITLES = {
    mediMindAI: 'MEDIMIND AI',
    searchMedicine: 'SEARCH MEDICINE',
    loginSignup: 'LOGIN/SIGNUP',
    landingPageTitle: 'AI-Powered Prescription Assistance',
    login: 'Login',
    signin: 'Sign In',
    signup: 'Sign Up',
    fullname: 'Full Name',
    email: 'email',
    password: 'password',
    confirmPassword: 'Confirm Password',
    signupFree: 'Sign Up Free!',
    bmi: 'Body Mass Index (BMI)',
    height: 'Height',
    weight: 'Weight',
    bodyMassIndex: 'Body Mass Index',
    youAreHealthy: `You're healthy`,
    bodyMeasurement: 'Body Measurements',
    invertedTraingleShape: 'Inverted triangle body shape',
    chest: 'Chest (in)',
    waist: 'Waist (in)',
    hip: 'Hip (in)',
}